
project_id = "lrlrwzzuxzjprcwktaff"

[functions.generate-blog]
verify_jwt = true

[functions.generate-blog-gemini]
verify_jwt = true

[functions.twitter-auth]
verify_jwt = true

[functions.twitter-fetch]
verify_jwt = true

[functions.linkedin-auth]
verify_jwt = true

[functions.linkedin-fetch]
verify_jwt = true
