// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrlrwzzuxzjprcwktaff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxybHJ3enp1eHpqcHJjd2t0YWZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1ODgxOTMsImV4cCI6MjA2MjE2NDE5M30.fDpcXVcFE8QwWLazQ3v6l6JOTYN2cfK1-jlsSVbuhlQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);